version: '3'

services:
  web:
    image: frontendv2:latest 
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
       - APP_ENV=local
       - APP_KEY=base64:7W53RBVKxU7ql0yBaGhaybldtRiWWpNOmAJWLX1Ulbk=  
       - APP_DEBUG=true
       - APP_URL=http://localhost
    depends_on:
       - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "5000:5001"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=auto_ecole
    volumes:
      - db_data:/var/lib/mysql
    container_name: auto_ecole

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8001:80"  # Forward port 80 of the container to port 8001 on the host
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # Mount the Nginx configuration file
  #   depends_on:
  #     - web

volumes:
  db_data:  # Define the volume here
